[2023-07-21T10:34:01.319+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2023-07-21T10:29:15.622665+00:00 [queued]>
[2023-07-21T10:34:01.340+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2023-07-21T10:29:15.622665+00:00 [queued]>
[2023-07-21T10:34:01.342+0000] {taskinstance.py:1308} INFO - Starting attempt 4 of 9
[2023-07-21T10:34:01.366+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-07-21 10:29:15.622665+00:00
[2023-07-21T10:34:01.375+0000] {standard_task_runner.py:57} INFO - Started process 391 to run task
[2023-07-21T10:34:01.385+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'first_task', 'manual__2023-07-21T10:29:15.622665+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/first_dag_bash_operator.py', '--cfg-path', '/tmp/tmpv9cr6dnu']
[2023-07-21T10:34:01.387+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask first_task
[2023-07-21T10:34:01.542+0000] {task_command.py:410} INFO - Running <TaskInstance: our_first_dag.first_task manual__2023-07-21T10:29:15.622665+00:00 [running]> on host 19c0c06e52d1
[2023-07-21T10:34:01.675+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manohar' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-21T10:29:15.622665+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-21T10:29:15.622665+00:00'
[2023-07-21T10:34:01.687+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-21T10:34:01.688+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello this is the first task']
[2023-07-21T10:34:01.707+0000] {subprocess.py:86} INFO - Output:
[2023-07-21T10:34:01.722+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-07-21T10:34:01.724+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-07-21T10:34:01.749+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-21T10:34:01.764+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=first_task, execution_date=20230721T102915, start_date=20230721T103401, end_date=20230721T103401
[2023-07-21T10:34:01.788+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 21 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 391)
[2023-07-21T10:34:01.802+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-21T10:34:01.828+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
