[2023-07-21T10:42:08.740+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2023-07-21T10:29:15.622665+00:00 [queued]>
[2023-07-21T10:42:08.752+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2023-07-21T10:29:15.622665+00:00 [queued]>
[2023-07-21T10:42:08.753+0000] {taskinstance.py:1308} INFO - Starting attempt 8 of 9
[2023-07-21T10:42:08.773+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-07-21 10:29:15.622665+00:00
[2023-07-21T10:42:08.779+0000] {standard_task_runner.py:57} INFO - Started process 554 to run task
[2023-07-21T10:42:08.782+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'first_task', 'manual__2023-07-21T10:29:15.622665+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/first_dag_bash_operator.py', '--cfg-path', '/tmp/tmp5ruyhep_']
[2023-07-21T10:42:08.784+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask first_task
[2023-07-21T10:42:08.833+0000] {task_command.py:410} INFO - Running <TaskInstance: our_first_dag.first_task manual__2023-07-21T10:29:15.622665+00:00 [running]> on host 19c0c06e52d1
[2023-07-21T10:42:08.914+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manohar' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-21T10:29:15.622665+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-21T10:29:15.622665+00:00'
[2023-07-21T10:42:08.917+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-21T10:42:08.919+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello this is the first task']
[2023-07-21T10:42:08.936+0000] {subprocess.py:86} INFO - Output:
[2023-07-21T10:42:08.948+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-07-21T10:42:08.949+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-07-21T10:42:08.965+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-21T10:42:08.972+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=first_task, execution_date=20230721T102915, start_date=20230721T104208, end_date=20230721T104208
[2023-07-21T10:42:08.996+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 30 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 554)
[2023-07-21T10:42:09.035+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-21T10:42:09.055+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
