[2023-07-21T10:44:09.952+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2023-07-21T10:29:15.622665+00:00 [queued]>
[2023-07-21T10:44:09.970+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2023-07-21T10:29:15.622665+00:00 [queued]>
[2023-07-21T10:44:09.971+0000] {taskinstance.py:1308} INFO - Starting attempt 9 of 9
[2023-07-21T10:44:09.991+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-07-21 10:29:15.622665+00:00
[2023-07-21T10:44:10.003+0000] {standard_task_runner.py:57} INFO - Started process 597 to run task
[2023-07-21T10:44:10.006+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'first_task', 'manual__2023-07-21T10:29:15.622665+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/first_dag_bash_operator.py', '--cfg-path', '/tmp/tmp9hosugi5']
[2023-07-21T10:44:10.008+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask first_task
[2023-07-21T10:44:10.068+0000] {task_command.py:410} INFO - Running <TaskInstance: our_first_dag.first_task manual__2023-07-21T10:29:15.622665+00:00 [running]> on host 19c0c06e52d1
[2023-07-21T10:44:10.156+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manohar' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-21T10:29:15.622665+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-21T10:29:15.622665+00:00'
[2023-07-21T10:44:10.162+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-21T10:44:10.163+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello this is the first task']
[2023-07-21T10:44:10.178+0000] {subprocess.py:86} INFO - Output:
[2023-07-21T10:44:10.188+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-07-21T10:44:10.189+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-07-21T10:44:10.205+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-21T10:44:10.212+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=our_first_dag, task_id=first_task, execution_date=20230721T102915, start_date=20230721T104409, end_date=20230721T104410
[2023-07-21T10:44:10.235+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 32 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 597)
[2023-07-21T10:44:10.264+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-21T10:44:10.286+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
