[2023-07-21T10:40:07.779+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2023-07-21T10:29:15.622665+00:00 [queued]>
[2023-07-21T10:40:07.803+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2023-07-21T10:29:15.622665+00:00 [queued]>
[2023-07-21T10:40:07.803+0000] {taskinstance.py:1308} INFO - Starting attempt 7 of 9
[2023-07-21T10:40:07.841+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-07-21 10:29:15.622665+00:00
[2023-07-21T10:40:07.849+0000] {standard_task_runner.py:57} INFO - Started process 509 to run task
[2023-07-21T10:40:07.858+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'first_task', 'manual__2023-07-21T10:29:15.622665+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/first_dag_bash_operator.py', '--cfg-path', '/tmp/tmpxn7o7kxp']
[2023-07-21T10:40:07.861+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask first_task
[2023-07-21T10:40:07.953+0000] {task_command.py:410} INFO - Running <TaskInstance: our_first_dag.first_task manual__2023-07-21T10:29:15.622665+00:00 [running]> on host 19c0c06e52d1
[2023-07-21T10:40:08.075+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manohar' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-21T10:29:15.622665+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-21T10:29:15.622665+00:00'
[2023-07-21T10:40:08.081+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-21T10:40:08.084+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello this is the first task']
[2023-07-21T10:40:08.099+0000] {subprocess.py:86} INFO - Output:
[2023-07-21T10:40:08.113+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-07-21T10:40:08.114+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-07-21T10:40:08.132+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-21T10:40:08.140+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=first_task, execution_date=20230721T102915, start_date=20230721T104007, end_date=20230721T104008
[2023-07-21T10:40:08.160+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 27 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 509)
[2023-07-21T10:40:08.195+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-21T10:40:08.223+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
