[2023-07-21T10:22:05.233+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2023-07-21T10:21:59.603155+00:00 [queued]>
[2023-07-21T10:22:05.259+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2023-07-21T10:21:59.603155+00:00 [queued]>
[2023-07-21T10:22:05.260+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-07-21T10:22:05.287+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-07-21 10:21:59.603155+00:00
[2023-07-21T10:22:05.296+0000] {standard_task_runner.py:57} INFO - Started process 156 to run task
[2023-07-21T10:22:05.305+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'first_task', 'manual__2023-07-21T10:21:59.603155+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/first_dag_bash_operator.py', '--cfg-path', '/tmp/tmpefq11xxk']
[2023-07-21T10:22:05.311+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask first_task
[2023-07-21T10:22:05.412+0000] {task_command.py:410} INFO - Running <TaskInstance: our_first_dag.first_task manual__2023-07-21T10:21:59.603155+00:00 [running]> on host 19c0c06e52d1
[2023-07-21T10:22:05.527+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manohar' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-21T10:21:59.603155+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-21T10:21:59.603155+00:00'
[2023-07-21T10:22:05.536+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-21T10:22:05.537+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello this is the first task']
[2023-07-21T10:22:05.551+0000] {subprocess.py:86} INFO - Output:
[2023-07-21T10:22:05.553+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-07-21T10:22:05.554+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-07-21T10:22:05.569+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-21T10:22:05.579+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=first_task, execution_date=20230721T102159, start_date=20230721T102205, end_date=20230721T102205
[2023-07-21T10:22:05.600+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 13 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 156)
[2023-07-21T10:22:05.651+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-21T10:22:05.681+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
