[2023-07-21T10:40:19.409+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2023-07-21T10:34:15.251219+00:00 [queued]>
[2023-07-21T10:40:19.427+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.first_task manual__2023-07-21T10:34:15.251219+00:00 [queued]>
[2023-07-21T10:40:19.427+0000] {taskinstance.py:1308} INFO - Starting attempt 4 of 6
[2023-07-21T10:40:19.447+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2023-07-21 10:34:15.251219+00:00
[2023-07-21T10:40:19.458+0000] {standard_task_runner.py:57} INFO - Started process 521 to run task
[2023-07-21T10:40:19.463+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'first_task', 'manual__2023-07-21T10:34:15.251219+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/first_dag_bash_operator.py', '--cfg-path', '/tmp/tmp17kbci8o']
[2023-07-21T10:40:19.465+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask first_task
[2023-07-21T10:40:19.535+0000] {task_command.py:410} INFO - Running <TaskInstance: our_first_dag.first_task manual__2023-07-21T10:34:15.251219+00:00 [running]> on host 19c0c06e52d1
[2023-07-21T10:40:19.637+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manohar' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-21T10:34:15.251219+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-21T10:34:15.251219+00:00'
[2023-07-21T10:40:19.640+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-21T10:40:19.641+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'hello this is the first task']
[2023-07-21T10:40:19.659+0000] {subprocess.py:86} INFO - Output:
[2023-07-21T10:40:19.667+0000] {subprocess.py:93} INFO - /bin/bash: line 1: hello: command not found
[2023-07-21T10:40:19.668+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-07-21T10:40:19.681+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-21T10:40:19.688+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=first_task, execution_date=20230721T103415, start_date=20230721T104019, end_date=20230721T104019
[2023-07-21T10:40:19.709+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 28 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 521)
[2023-07-21T10:40:19.755+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-21T10:40:19.780+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
