[2023-07-21T11:06:13.198+0000] {processor.py:157} INFO - Started process (PID=833) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:06:13.200+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:06:13.201+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:06:13.201+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:06:13.243+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:06:13.225+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:06:13.246+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:06:13.320+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.127 seconds
[2023-07-21T11:06:43.695+0000] {processor.py:157} INFO - Started process (PID=843) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:06:43.699+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:06:43.702+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:06:43.701+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:06:43.736+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:06:43.726+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:06:43.738+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:06:43.806+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.118 seconds
[2023-07-21T11:07:14.266+0000] {processor.py:157} INFO - Started process (PID=852) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:07:14.268+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:07:14.270+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:07:14.269+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:07:14.310+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:07:14.298+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:07:14.313+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:07:14.374+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.115 seconds
[2023-07-21T11:07:44.727+0000] {processor.py:157} INFO - Started process (PID=862) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:07:44.729+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:07:44.732+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:07:44.730+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:07:44.768+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:07:44.759+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:07:44.770+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:07:44.839+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.119 seconds
[2023-07-21T11:08:15.206+0000] {processor.py:157} INFO - Started process (PID=871) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:08:15.209+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:08:15.213+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:08:15.210+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:08:15.248+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:08:15.237+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:08:15.250+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:08:15.341+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.145 seconds
[2023-07-21T11:08:45.758+0000] {processor.py:157} INFO - Started process (PID=880) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:08:45.765+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:08:45.768+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:08:45.766+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:08:45.819+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:08:45.805+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:08:45.821+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:08:55.874+0000] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 162, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 842, in process_file
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 620, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(errors.ImportError.filename).all()]
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2919, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1556, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3375, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2209, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-07-21T11:09:28.036+0000] {processor.py:157} INFO - Started process (PID=889) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:09:28.038+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:09:28.042+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:09:28.040+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:09:28.082+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:09:28.071+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:09:28.084+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:09:28.162+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.140 seconds
[2023-07-21T11:09:58.930+0000] {processor.py:157} INFO - Started process (PID=899) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:09:58.932+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:09:58.937+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:09:58.933+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:09:58.981+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:09:58.969+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:09:58.984+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:09:59.082+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.163 seconds
[2023-07-21T11:10:29.386+0000] {processor.py:157} INFO - Started process (PID=908) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:10:29.423+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:10:29.470+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:10:29.450+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:10:29.625+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:10:29.569+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:10:29.673+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:10:35.538+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 6.186 seconds
[2023-07-21T11:11:06.080+0000] {processor.py:157} INFO - Started process (PID=918) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:11:06.082+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:11:06.085+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:11:06.084+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:11:06.121+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:11:06.108+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:11:06.123+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:11:06.167+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.095 seconds
[2023-07-21T11:11:36.568+0000] {processor.py:157} INFO - Started process (PID=927) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:11:36.569+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:11:36.571+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:11:36.570+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:11:36.595+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:11:36.586+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:11:36.596+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:11:36.617+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.053 seconds
[2023-07-21T11:12:07.042+0000] {processor.py:157} INFO - Started process (PID=936) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:12:07.045+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:12:07.049+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:12:07.047+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:12:07.106+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:12:07.092+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:12:07.109+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:12:07.174+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.142 seconds
[2023-07-21T11:12:37.552+0000] {processor.py:157} INFO - Started process (PID=945) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:12:37.554+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:12:37.556+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:12:37.555+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:12:37.579+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:12:37.574+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:12:37.581+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:12:37.630+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.082 seconds
[2023-07-21T11:13:08.027+0000] {processor.py:157} INFO - Started process (PID=953) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:13:08.031+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:13:08.034+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:13:08.033+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:13:08.099+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:13:08.081+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:13:08.103+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:13:08.182+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.167 seconds
[2023-07-21T11:13:38.565+0000] {processor.py:157} INFO - Started process (PID=962) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:13:38.570+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:13:38.573+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:13:38.572+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:13:38.631+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:13:38.616+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:13:38.634+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:13:38.693+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.137 seconds
[2023-07-21T11:14:09.113+0000] {processor.py:157} INFO - Started process (PID=972) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:14:09.115+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:14:09.118+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:14:09.116+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:14:09.161+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:14:09.153+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:14:09.163+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:14:09.271+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.166 seconds
[2023-07-21T11:14:39.648+0000] {processor.py:157} INFO - Started process (PID=981) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:14:39.651+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:14:39.652+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:14:39.652+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:14:39.714+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:14:39.696+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:14:39.717+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:14:39.754+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.112 seconds
[2023-07-21T11:15:10.120+0000] {processor.py:157} INFO - Started process (PID=990) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:15:10.121+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:15:10.123+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:15:10.122+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:15:10.143+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:15:10.137+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:15:10.144+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:15:10.216+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.100 seconds
[2023-07-21T11:15:40.584+0000] {processor.py:157} INFO - Started process (PID=999) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:15:40.585+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:15:40.586+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:15:40.586+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:15:40.629+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:15:40.616+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:15:40.631+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:15:40.679+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.100 seconds
[2023-07-21T11:16:11.105+0000] {processor.py:157} INFO - Started process (PID=1008) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:16:11.107+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:16:11.110+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:16:11.109+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:16:11.163+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:16:11.148+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:16:11.167+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:16:11.219+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.122 seconds
[2023-07-21T11:16:41.614+0000] {processor.py:157} INFO - Started process (PID=1018) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:16:41.615+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:16:41.617+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:16:41.616+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:16:41.645+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:16:41.638+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:16:41.646+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:16:41.684+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.075 seconds
[2023-07-21T11:17:12.007+0000] {processor.py:157} INFO - Started process (PID=1027) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:17:12.010+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:17:12.011+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:17:12.010+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:17:12.036+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:17:12.029+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:17:12.037+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:17:12.100+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.097 seconds
[2023-07-21T11:17:42.530+0000] {processor.py:157} INFO - Started process (PID=1036) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:17:42.531+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:17:42.534+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:17:42.533+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:17:42.580+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:17:42.569+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:17:42.582+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:17:42.635+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.111 seconds
[2023-07-21T11:18:13.065+0000] {processor.py:157} INFO - Started process (PID=1045) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:18:13.067+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:18:13.069+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:18:13.068+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:18:13.112+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:18:13.099+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:18:13.114+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:18:13.195+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.144 seconds
[2023-07-21T11:18:43.556+0000] {processor.py:157} INFO - Started process (PID=1054) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:18:43.559+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:18:43.563+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:18:43.561+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:18:43.606+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:18:43.597+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:18:43.609+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:18:43.634+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.089 seconds
[2023-07-21T11:19:14.038+0000] {processor.py:157} INFO - Started process (PID=1063) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:19:14.040+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:19:14.044+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:19:14.042+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:19:14.070+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:19:14.063+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:19:14.072+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:19:14.111+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.077 seconds
[2023-07-21T11:19:44.456+0000] {processor.py:157} INFO - Started process (PID=1072) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:19:44.458+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:19:44.460+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:19:44.459+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:19:44.481+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:19:44.476+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:19:44.482+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:19:44.508+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.056 seconds
[2023-07-21T11:20:14.882+0000] {processor.py:157} INFO - Started process (PID=1081) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:20:14.884+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:20:14.885+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:20:14.884+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:20:14.905+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:20:14.899+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:20:14.907+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:20:14.940+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.063 seconds
[2023-07-21T11:20:45.305+0000] {processor.py:157} INFO - Started process (PID=1090) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:20:45.306+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:20:45.307+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:20:45.307+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:20:45.330+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:20:45.323+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:20:45.331+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:20:45.357+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.057 seconds
[2023-07-21T11:21:15.785+0000] {processor.py:157} INFO - Started process (PID=1099) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:21:15.786+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:21:15.787+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:21:15.787+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:21:15.809+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:21:15.805+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:21:15.810+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:21:15.830+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.049 seconds
[2023-07-21T11:21:46.174+0000] {processor.py:157} INFO - Started process (PID=1108) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:21:46.176+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:21:46.179+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:21:46.177+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:21:46.212+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:21:46.203+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:21:46.214+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:21:46.260+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.093 seconds
[2023-07-21T11:22:16.610+0000] {processor.py:157} INFO - Started process (PID=1117) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:22:16.612+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:22:16.613+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:22:16.613+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:22:16.654+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:22:16.642+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:22:16.657+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:22:16.695+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.092 seconds
[2023-07-21T11:22:47.039+0000] {processor.py:157} INFO - Started process (PID=1127) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:22:47.041+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:22:47.043+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:22:47.042+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:22:47.078+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:22:47.067+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:22:47.080+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:22:47.150+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.116 seconds
[2023-07-21T11:23:17.563+0000] {processor.py:157} INFO - Started process (PID=1137) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:23:17.568+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:23:17.571+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:23:17.570+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:23:17.618+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:23:17.606+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:23:17.621+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:23:17.673+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.124 seconds
[2023-07-21T11:23:48.007+0000] {processor.py:157} INFO - Started process (PID=1146) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:23:48.010+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:23:48.012+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:23:48.011+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:23:48.060+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:23:48.048+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:23:48.062+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:23:48.095+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.093 seconds
[2023-07-21T11:24:18.434+0000] {processor.py:157} INFO - Started process (PID=1155) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:24:18.436+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:24:18.437+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:24:18.437+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:24:18.468+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:24:18.459+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:24:18.470+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:24:18.504+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.074 seconds
[2023-07-21T11:24:49.020+0000] {processor.py:157} INFO - Started process (PID=1164) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:24:49.022+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:24:49.024+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:24:49.024+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:24:49.059+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:24:49.049+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:24:49.062+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:24:49.135+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.126 seconds
[2023-07-21T11:25:19.559+0000] {processor.py:157} INFO - Started process (PID=1173) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:25:19.560+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:25:19.563+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:25:19.563+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:25:19.598+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:25:19.588+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:25:19.600+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:25:19.641+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.090 seconds
[2023-07-21T11:25:50.026+0000] {processor.py:157} INFO - Started process (PID=1182) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:25:50.029+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:25:50.033+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:25:50.030+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:25:50.081+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:25:50.069+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:25:50.085+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:25:50.128+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.111 seconds
[2023-07-21T11:26:20.532+0000] {processor.py:157} INFO - Started process (PID=1192) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:26:20.535+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:26:20.536+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:26:20.535+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:26:20.577+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:26:20.567+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:26:20.580+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:26:20.610+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.083 seconds
[2023-07-21T11:26:50.910+0000] {processor.py:157} INFO - Started process (PID=1201) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:26:50.912+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:26:50.913+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:26:50.913+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:26:50.944+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:26:50.938+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:26:50.946+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:26:50.977+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.070 seconds
[2023-07-21T11:27:21.307+0000] {processor.py:157} INFO - Started process (PID=1210) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:27:21.309+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:27:21.310+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:27:21.310+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:27:21.340+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:27:21.333+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:27:21.342+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:27:21.374+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.072 seconds
[2023-07-21T11:27:51.673+0000] {processor.py:157} INFO - Started process (PID=1219) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:27:51.675+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:27:51.676+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:27:51.676+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:27:51.705+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:27:51.699+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:27:51.707+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:27:51.736+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.067 seconds
[2023-07-21T11:28:22.061+0000] {processor.py:157} INFO - Started process (PID=1228) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:28:22.063+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:28:22.065+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:28:22.064+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:28:22.095+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:28:22.089+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:28:22.097+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:28:22.128+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.071 seconds
[2023-07-21T11:28:52.492+0000] {processor.py:157} INFO - Started process (PID=1237) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:28:52.494+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:28:52.497+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:28:52.496+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:28:52.531+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:28:52.524+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:28:52.533+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:28:52.590+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.105 seconds
[2023-07-21T11:29:22.925+0000] {processor.py:157} INFO - Started process (PID=1246) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:29:22.926+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:29:22.928+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:29:22.928+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:29:22.962+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:29:22.953+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:29:22.964+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:29:23.001+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.080 seconds
[2023-07-21T11:29:53.338+0000] {processor.py:157} INFO - Started process (PID=1255) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:29:53.340+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:29:53.341+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:29:53.341+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:29:53.386+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:29:53.377+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:29:53.389+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:29:53.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.086 seconds
[2023-07-21T11:30:23.742+0000] {processor.py:157} INFO - Started process (PID=1264) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:30:23.744+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:30:23.745+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:30:23.745+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:30:23.780+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:30:23.771+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:30:23.782+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:30:23.815+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.077 seconds
[2023-07-21T11:30:54.176+0000] {processor.py:157} INFO - Started process (PID=1273) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:30:54.177+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:30:54.179+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:30:54.178+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:30:54.218+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:30:54.210+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:30:54.221+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:30:54.259+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.089 seconds
[2023-07-21T11:31:24.637+0000] {processor.py:157} INFO - Started process (PID=1282) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:31:24.640+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:31:24.641+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:31:24.641+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:31:24.673+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:31:24.664+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:31:24.674+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:31:24.707+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.076 seconds
[2023-07-21T11:31:55.080+0000] {processor.py:157} INFO - Started process (PID=1291) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:31:55.083+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:31:55.084+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:31:55.084+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:31:55.115+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:31:55.109+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:31:55.117+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:31:55.195+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.123 seconds
[2023-07-21T11:32:25.534+0000] {processor.py:157} INFO - Started process (PID=1300) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:32:25.535+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:32:25.538+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:32:25.536+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:32:25.567+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:32:25.557+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:32:25.569+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:32:25.601+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.074 seconds
[2023-07-21T11:32:56.139+0000] {processor.py:157} INFO - Started process (PID=1310) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:32:56.141+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:32:56.144+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:32:56.142+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:32:56.172+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:32:56.167+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:32:56.173+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:32:56.201+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.072 seconds
[2023-07-21T11:33:26.621+0000] {processor.py:157} INFO - Started process (PID=1319) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:33:26.624+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:33:26.629+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:33:26.625+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:33:26.699+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:33:26.677+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:33:26.702+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:33:26.789+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.176 seconds
[2023-07-21T11:33:57.656+0000] {processor.py:157} INFO - Started process (PID=1328) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:33:57.657+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:33:57.660+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:33:57.658+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:33:57.688+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:33:57.679+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:33:57.690+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:33:57.919+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.271 seconds
[2023-07-21T11:34:28.578+0000] {processor.py:157} INFO - Started process (PID=1338) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:34:28.661+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:34:28.667+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:34:28.663+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:34:28.717+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:34:28.707+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:34:28.720+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:34:29.013+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.443 seconds
[2023-07-21T11:34:59.942+0000] {processor.py:157} INFO - Started process (PID=1347) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:34:59.947+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:34:59.950+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:34:59.950+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:35:00.912+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:35:00.829+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:35:00.918+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:35:02.224+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 2.294 seconds
[2023-07-21T11:35:32.873+0000] {processor.py:157} INFO - Started process (PID=1356) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:35:32.875+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:35:32.878+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:35:32.877+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:35:32.920+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:35:32.909+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:35:32.922+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:35:33.269+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.406 seconds
[2023-07-21T11:36:03.960+0000] {processor.py:157} INFO - Started process (PID=1366) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:36:03.962+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:36:03.965+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:36:03.963+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:36:04.001+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:36:03.989+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:36:04.003+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:36:04.287+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.336 seconds
[2023-07-21T11:36:34.787+0000] {processor.py:157} INFO - Started process (PID=1375) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:36:34.790+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:36:34.792+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:36:34.791+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:36:34.882+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:36:34.873+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:36:34.883+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:36:34.935+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.155 seconds
[2023-07-21T11:37:05.640+0000] {processor.py:157} INFO - Started process (PID=1384) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:37:05.842+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:37:05.846+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:37:05.845+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:37:05.998+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:37:05.911+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:37:06.001+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:37:06.055+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.432 seconds
[2023-07-21T11:37:36.534+0000] {processor.py:157} INFO - Started process (PID=1394) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:37:36.538+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:37:36.562+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:37:36.554+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:37:36.666+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:37:36.640+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:37:36.670+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:37:36.884+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.416 seconds
[2023-07-21T11:38:07.582+0000] {processor.py:157} INFO - Started process (PID=1403) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:38:07.584+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:38:07.585+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:38:07.585+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:38:07.610+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:38:07.603+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:38:07.612+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:38:07.646+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.068 seconds
[2023-07-21T11:42:55.576+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:42:55.578+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:42:55.580+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:42:55.579+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:42:55.619+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:42:55.609+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:42:55.622+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:42:55.660+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.090 seconds
[2023-07-21T11:43:26.209+0000] {processor.py:157} INFO - Started process (PID=41) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:43:26.214+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:43:26.222+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:43:26.221+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:43:26.268+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:43:26.257+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:43:26.272+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:43:26.371+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.189 seconds
[2023-07-21T11:43:56.727+0000] {processor.py:157} INFO - Started process (PID=49) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:43:56.730+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:43:56.731+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:43:56.731+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:43:56.788+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:43:56.770+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:43:56.791+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:43:56.827+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.104 seconds
[2023-07-21T11:44:27.211+0000] {processor.py:157} INFO - Started process (PID=59) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:44:27.213+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:44:27.214+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:44:27.214+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:44:27.260+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:44:27.251+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:44:27.263+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:44:27.294+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.091 seconds
[2023-07-21T11:44:57.605+0000] {processor.py:157} INFO - Started process (PID=68) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:44:57.607+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:44:57.609+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:44:57.608+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:44:57.642+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:44:57.636+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:44:57.645+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:44:57.671+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.069 seconds
[2023-07-21T11:45:28.088+0000] {processor.py:157} INFO - Started process (PID=77) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:45:28.091+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:45:28.097+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:45:28.096+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:45:28.633+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:45:28.628+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:45:28.635+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:45:28.656+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.575 seconds
[2023-07-21T11:45:58.754+0000] {processor.py:157} INFO - Started process (PID=94) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:45:58.756+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:45:58.758+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:45:58.757+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:45:58.798+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:45:58.790+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:45:58.801+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:45:58.826+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.076 seconds
[2023-07-21T11:46:29.222+0000] {processor.py:157} INFO - Started process (PID=103) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:46:29.224+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:46:29.226+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:46:29.225+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:46:29.269+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:46:29.261+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:46:29.272+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:46:29.301+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.085 seconds
[2023-07-21T11:46:59.673+0000] {processor.py:157} INFO - Started process (PID=112) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:46:59.674+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:46:59.675+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:46:59.675+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:46:59.710+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:46:59.704+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:46:59.712+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:46:59.743+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.075 seconds
[2023-07-21T11:47:30.118+0000] {processor.py:157} INFO - Started process (PID=122) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:47:30.120+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:47:30.121+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:47:30.121+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:47:30.150+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:47:30.144+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:47:30.152+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:47:30.178+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.063 seconds
[2023-07-21T11:48:00.634+0000] {processor.py:157} INFO - Started process (PID=131) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:48:00.635+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:48:00.637+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:48:00.636+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:48:00.671+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:48:00.666+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:48:00.673+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:48:00.701+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.071 seconds
[2023-07-21T11:48:31.095+0000] {processor.py:157} INFO - Started process (PID=140) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:48:31.097+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:48:31.099+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:48:31.099+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:48:31.145+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:48:31.136+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:48:31.148+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:48:31.187+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.101 seconds
[2023-07-21T11:49:01.604+0000] {processor.py:157} INFO - Started process (PID=149) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:49:01.606+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:49:01.608+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:49:01.608+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:49:01.645+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:49:01.637+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:49:01.648+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:49:01.684+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.086 seconds
[2023-07-21T11:49:32.332+0000] {processor.py:157} INFO - Started process (PID=159) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:49:32.337+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:49:32.340+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:49:32.339+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:49:32.408+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:49:32.390+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:49:32.414+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:49:32.467+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.180 seconds
[2023-07-21T11:50:02.656+0000] {processor.py:157} INFO - Started process (PID=172) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:50:02.660+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:50:02.663+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:50:02.662+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:50:02.717+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:50:02.706+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:50:02.721+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:50:02.767+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.119 seconds
[2023-07-21T11:50:33.166+0000] {processor.py:157} INFO - Started process (PID=182) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:50:33.168+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:50:33.171+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:50:33.170+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:50:33.211+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:50:33.203+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:50:33.214+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:50:33.261+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.104 seconds
[2023-07-21T11:51:03.682+0000] {processor.py:157} INFO - Started process (PID=191) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:51:03.684+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:51:03.685+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:51:03.685+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:51:03.720+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:51:03.710+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:51:03.723+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:51:03.767+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.095 seconds
[2023-07-21T11:51:34.178+0000] {processor.py:157} INFO - Started process (PID=200) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:51:34.181+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:51:34.183+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:51:34.182+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:51:34.229+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:51:34.221+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:51:34.233+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:51:34.279+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.108 seconds
[2023-07-21T11:52:04.776+0000] {processor.py:157} INFO - Started process (PID=209) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:52:04.780+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:52:04.786+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:52:04.784+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:52:04.836+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:52:04.824+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:52:04.840+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:52:04.925+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.226 seconds
[2023-07-21T11:52:35.294+0000] {processor.py:157} INFO - Started process (PID=218) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:52:35.296+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:52:35.297+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:52:35.297+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:52:35.328+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:52:35.323+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:52:35.331+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:52:35.357+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.067 seconds
[2023-07-21T11:53:05.757+0000] {processor.py:157} INFO - Started process (PID=231) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:53:05.759+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:53:05.761+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:53:05.761+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:53:05.794+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:53:05.788+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:53:05.797+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:53:05.822+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.069 seconds
[2023-07-21T11:53:36.306+0000] {processor.py:157} INFO - Started process (PID=240) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:53:36.309+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:53:36.312+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:53:36.311+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:53:36.369+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:53:36.359+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:53:36.373+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:53:36.434+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.139 seconds
[2023-07-21T11:54:06.880+0000] {processor.py:157} INFO - Started process (PID=250) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:54:06.882+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:54:06.885+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:54:06.885+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:54:06.934+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:54:06.924+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:54:06.939+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:54:06.989+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.117 seconds
[2023-07-21T11:54:37.398+0000] {processor.py:157} INFO - Started process (PID=260) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:54:37.400+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:54:37.405+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:54:37.402+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:54:37.440+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:54:37.434+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:54:37.442+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:54:37.483+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.091 seconds
[2023-07-21T11:55:07.911+0000] {processor.py:157} INFO - Started process (PID=269) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:55:07.913+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:55:07.915+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:55:07.915+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:55:07.959+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:55:07.949+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:55:07.963+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:55:08.025+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.124 seconds
[2023-07-21T11:55:38.388+0000] {processor.py:157} INFO - Started process (PID=278) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:55:38.390+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:55:38.392+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:55:38.392+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:55:38.429+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:55:38.421+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:55:38.431+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:55:38.463+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.080 seconds
[2023-07-21T11:56:08.854+0000] {processor.py:157} INFO - Started process (PID=287) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:56:08.855+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:56:08.857+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:56:08.857+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:56:08.922+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:56:08.883+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:56:08.924+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:56:08.951+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.105 seconds
[2023-07-21T11:56:39.398+0000] {processor.py:157} INFO - Started process (PID=296) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:56:39.401+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:56:39.403+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:56:39.402+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:56:39.452+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:56:39.442+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:56:39.455+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:56:39.499+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.111 seconds
[2023-07-21T11:57:09.882+0000] {processor.py:157} INFO - Started process (PID=305) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:57:09.883+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:57:09.884+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:57:09.884+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:57:09.909+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:57:09.903+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:57:09.911+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:57:09.934+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.056 seconds
[2023-07-21T11:57:40.327+0000] {processor.py:157} INFO - Started process (PID=315) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:57:40.329+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:57:40.331+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:57:40.330+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:57:40.370+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:57:40.359+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:57:40.374+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:57:40.414+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.093 seconds
[2023-07-21T11:58:10.833+0000] {processor.py:157} INFO - Started process (PID=324) to work on /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:58:10.835+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/second_dag_python.py for tasks to queue
[2023-07-21T11:58:10.837+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:58:10.837+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:58:10.896+0000] {logging_mixin.py:150} INFO - [2023-07-21T11:58:10.878+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/second_dag_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/second_dag_python.py", line 4, in <module>
    from airflow.operators.python import pythonoperator
ImportError: cannot import name 'pythonoperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2023-07-21T11:58:10.901+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/second_dag_python.py
[2023-07-21T11:58:10.950+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/second_dag_python.py took 0.122 seconds
